=== datazuul/jbal/engine/src/org/jopac2/conf/dataDefinition/class.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT class (xmlmapping?,description)>
<!ELEMENT description (filter?,AUT?,TIT?,NUM?,LAN?,MAT?,DTE?,SBJ?,BIB?,INV?,CLL?,ANY?,ABS?)>
<!ELEMENT element EMPTY>
<!ATTLIST class name CDATA #REQUIRED>
<!ATTLIST element tag CDATA #REQUIRED
                  field CDATA #REQUIRED
                  comment CDATA #IMPLIED
                  name CDATA #IMPLIED
                  >
<!ATTLIST xmlmapping root CDATA #REQUIRED
				  record CDATA #REQUIRED
				  >
<!ELEMENT xmlmapping (element*)>   
<!ELEMENT filter (element*)>               
<!ELEMENT AUT (element*)>
<!ELEMENT TIT (element*)>
<!ELEMENT NUM (element*)>
<!ELEMENT LAN (element*)>
<!ELEMENT MAT (element*)>
<!ELEMENT DTE (element*)>
<!ELEMENT SBJ (element*)>
<!ELEMENT BIB (element*)>
<!ELEMENT INV (element*)>
<!ELEMENT CLL (element*)>
<!ELEMENT ANY (element*)>
<!ELEMENT ABS (element*)>

=== datazuul/jbal/JSites/WebContent/WEB-INF/conf/engine/dataDefinition/pregresso.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE class SYSTEM 'class.dtd'>

<!--
    Document   : pregresso.xml
    Created on : 16 gennaio 2004, 21.25
    Author     : romano
    Description:
        Purpose of the document follows.
-->

<class name="Pregresso">
<description>

<!--        
    iso.addTag("100"+iso.dl+"a"+r.getString("testoHtml"));
    iso.addTag("200"+iso.dl+"a"+r.getString("testoTxt"));
    iso.addTag("300"+iso.dl+"a"+r.getString("autore"));
    iso.addTag("310"+iso.dl+"a"+r.getString("isbd"));
    iso.addTag("320"+iso.dl+"a"+r.getString("isbn"));
    iso.addTag("330"+iso.dl+"a"+r.getString("inventario")+iso.dl+"b"+r.getString("collocazione"));
    iso.addTag("340"+iso.dl+"a"+r.getString("data_ins"));
-->
    <TIT>
        <!-- element tag="200" field="a" / -->
        <element tag="300" field="a" />
        <element tag="310" field="a" />
        
        <element tag="320" field="a" />
        <element tag="330" field="a" />
        <element tag="330" field="b" />
    </TIT>
    
    
</description>
</class>

=== datazuul/jbal/JSites/WebContent/WEB-INF/conf/engine/dataDefinition/isisbiblo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : isisbiblo.xml
    Created on : 16 gennaio 2004, 21.16
    Author     : romano
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE class SYSTEM 'class.dtd'>
<class name="Isisbiblo">
<description>
	<AUT>
            <element tag="011" field="R" />
            <element tag="011" field="A" />
            <element tag="012" field="R" />
            <element tag="014" field="N" />
            <element tag="021" field="R" />
            <element tag="021" field="A" />
            <element tag="031" field="R" />
            <element tag="031" field="A" />
            <element tag="041" field="C" />
            <element tag="041" field="N" />
            <element tag="051" field="C" />
            <element tag="051" field="N" />
            <element tag="054" field="C" />
            <element tag="054" field="N" />
            
            <element tag="011" field="r" />
            <element tag="011" field="a" />
            <element tag="012" field="r" />
            <element tag="014" field="n" />
            <element tag="021" field="r" />
            <element tag="021" field="a" />
            <element tag="031" field="r" />
            <element tag="031" field="a" />
            <element tag="041" field="c" />
            <element tag="041" field="n" />
            <element tag="051" field="c" />
            <element tag="051" field="n" />
            <element tag="054" field="c" />
            <element tag="054" field="n" />
	</AUT>
	<TIT>
            <element tag="011" field="T" />
            <element tag="011" field="C" />
            <element tag="011" field="P" />
            <element tag="011" field="S" />
            <element tag="021" field="T" />
            <element tag="021" field="C" />
            <element tag="021" field="P" />
            <element tag="021" field="S" />
            <element tag="031" field="T" />
            <element tag="031" field="C" />
            <element tag="031" field="P" />
            <element tag="031" field="S" />
            <element tag="045" field="T" />
            <element tag="045" field="P" />
            
            <element tag="011" field="t" />
            <element tag="011" field="c" />
            <element tag="011" field="p" />
            <element tag="011" field="s" />
            <element tag="021" field="t" />
            <element tag="021" field="c" />
            <element tag="021" field="p" />
            <element tag="021" field="s" />
            <element tag="031" field="t" />
            <element tag="031" field="c" />
            <element tag="031" field="p" />
            <element tag="031" field="s" />
            <element tag="045" field="t" />
            <element tag="045" field="p" />
     </TIT>
   	<NUM>
            <element tag="018" field="B" />
            <element tag="018" field="S" />
			<element tag="018" field="b" />
            <element tag="018" field="s" />
	</NUM>
     <CLL>
            <element tag="016" field="T" />
            <element tag="016" field="P" />
            <element tag="016" field="C" />
            
            <element tag="016" field="t" />
            <element tag="016" field="p" />
            <element tag="016" field="c" />            
	</CLL>

</description>
</class>

=== datazuul/jbal/JSites/WebContent/WEB-INF/conf/engine/dataDefinition/bibliowin4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
	Document   : bibliowin4.xml
	Created on : 14 settembre 2004, 19.45
	Author     : romano
	Description:
	Purpose of the document follows.
-->

<!DOCTYPE class SYSTEM 'class.dtd'>
<class name="Bibliowin4">
	<description>
		<AUT>
			<element tag="700" field="a" />
			<element tag="702" field="a" />
		</AUT>
		<TIT>
			<element tag="200" field="a" />
			<element tag="200" field="e" />
			<element tag="225" field="a" />
			<element tag="300" field="a" />
		</TIT>
		<NUM>
			<element tag="010" field="a" />
		</NUM>
		<LAN>
			<element tag="101" field="a" />
		</LAN>
		<DTE>
			<element tag="211" field="a" />
		</DTE>
		<SBJ>
			<element tag="610" field="a" />
		</SBJ>
		<BIB>
			<element tag="950" field="j" />
		</BIB>
		<INV>
			<element tag="950" field="c" />
		</INV>
		<CLL>
			<element tag="913" field="a" />
		</CLL>
	</description>
</class>

=== datazuul/jbal/JSites/WebContent/WEB-INF/conf/engine/dataDefinition/easyweb.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE class SYSTEM 'class.dtd'>

<class name="Easyweb">
<description>
	<AUT>
            <element tag="710" field="a" />
            <element tag="711" field="a" />
            <element tag="712" field="a" />
	</AUT>
	<TIT>
            <element tag="997" field="a" />
	</TIT>
	<LAN>
            <element tag="030" field="a" />
	</LAN>
	<MAT>
            <element tag="040" field="a" />
	</MAT>	
	<SBJ>
            <element tag="730" field="a" />
	</SBJ>
	<BIB>
            <element tag="800" field="a" />
            <element tag="800" field="b" />
	</BIB>
	<INV>
            <element tag="800" field="d" />
	</INV>
	<CLL>
            <element tag="420" field="a" />
	</CLL>
</description>
</class>

=== datazuul/jbal/engine/src/org/jopac2/conf/dataDefinition/eutmarc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE class SYSTEM 'class.dtd'>

<!--
    Document   : sebina.xml
    Created on : 16 gennaio 2004, 21.28
    Author     : romano
    Description:
        Purpose of the document follows.
-->

<class  name="Eutmarc">
<description>
	<AUT>
            <element tag="200" field="f" comment="ciao" />
            <element tag="200" field="g" />
            <element tag="700" field="a" />
            <element tag="700" field="b" />
            <element tag="700" field="c" />
            <element tag="701" field="a" />
            <element tag="701" field="b" />
            <element tag="701" field="c" />
            <element tag="702" field="a" />
            <element tag="702" field="b" />
            <element tag="702" field="c" />
	</AUT>
	<TIT>
            <element tag="200" field="a" />
            <element tag="200" field="c" />
            <element tag="200" field="d" />
            <element tag="200" field="e" />
            <element tag="500" field="a" />
            <element tag="510" field="a" />
            <element tag="517" field="a" />
	</TIT>
	<NUM>
            <element tag="010" field="a" />
            <element tag="011" field="a" />
            <element tag="013" field="a" />
	</NUM>
	<LAN>
            <element tag="101" field="a" />
	</LAN>
	<MAT>
            <element tag="200" field="b" />
	</MAT>
	<DTE>
            <element tag="500" field="k" />
	</DTE>
	<SBJ>
            <element tag="600" field="a" />
            <element tag="601" field="a" />
            <element tag="602" field="a" />
            <element tag="604" field="1" />
            <element tag="605" field="a" />
            <element tag="605" field="a" />
            <element tag="607" field="a" />
            <element tag="610" field="a" />
	</SBJ>
	<BIB>
            <element tag="899" field="a" />
	</BIB>
	<INV>
            <element tag="950" field="e" />
	</INV>
	<CLL>
            <element tag="410" field="a" />
	</CLL>
</description>
</class>

=== datazuul/jbal/JSites/WebContent/WEB-INF/conf/engine/dataDefinition/Eut.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE class SYSTEM 'class.dtd'>

<!--
    Document   : Eut.xml
    Created on : 1 giugno 2006, 22.12
    Author     : romano
    Description:
    
    <record> 
	 * 	<ID>1</ID> 
	 * 	<Titolo>Le due sponde del Mediterraneo : l'immagine riflessa; 473 p., 24 cm.</Titolo> 
	 * 	<Autore 1>null</Autore 1> 
	 * 	<Autore 2>null</Autore 2> 
	 * 	<Autore 3>null</Autore 3> 
	 * 	<Autore 4>null</Autore 4> 
	 * 	<ISBN>null</ISBN> 
	 * 	<Anno>1999.0</Anno> 
	 * 	<Prezzo>â‚¬ 20,00</Prezzo> 
	 * 	<Abstract>Presentazione ... </Abstract> 
	 * 	<File immagine>due_sponde_mediterraneo</File immagine> 
	 * </record>
        
-->

<class  name="Eut">



	<description>
	<!-- 
		<filter>
				<element tag="Eut.xslt" field="" />
		</filter>
	-->
		<AUT>
				<element tag="/record/Autore1" field="" />
				<element tag="/record/Autore2" field="" />
				<element tag="/record/Autore3" field="" />
				<element tag="/record/Autore4" field="" />
		</AUT>
		<TIT>
	            <element tag="/record/Titolo" field="" />
		</TIT>
		<NUM>
	            <element tag="/record/ISBN" field="" />
		</NUM>
		<ABS>
				<element tag="/record/Abstract" field="" />
		</ABS>
	</description>
	<!-- 
	<input>
		<record>
			<titolo cols="80" rows="3"></titolo>
			<autore cols="40" rows="3"></autore>
			<isbn></isbn>
			<anno>1999</anno>
			<prezzo>20</prezzo>
			<immagine>image001.jpg</immagine>
			<abstract></abstract>
		</record>
	</input>
	-->
</class>
