=== datazuul/jbal/JSites/WebContent/WEB-INF/conf/engine/dataDefinition/dataType.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT root (data*)>
<!ELEMENT data (name,description?)>
<!ELEMENT name (#PCDATA) >
<!ELEMENT description (#PCDATA) >

=== datazuul/jbal/engine/src/org/jopac2/conf/dataDefinition/dataType.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root SYSTEM 'dataType.dtd'>

<!--
    Document   : data-types.xml
    Created on : 18 gennaio 2004, 9.30
    Author     : romano
    Description:
        Purpose of the document follows.
-->

<root>
    <data>
        <name>Sebina</name>
        <description>Sebina SBN - Prodotto da Akros Informatica S.r.l.
            v.4.0.2
        </description>
    </data>
    <data>
        <name>Sosebi</name>
    </data>
    <data>
        <name>SBNUnix</name>
    </data>
    <data>
        <name>Isisbiblo</name>
    </data>
    <data>
        <name>Isisteca</name>
    </data>
    <data>
        <name>Easyweb</name>
    </data>
    <data>
        <name>Bibliowin4</name>
    </data>
    <data>
        <name>Mdb</name>
    </data>
    <data>
        <name>Pregresso</name>
        <description>Formato per il recupero del pregresso UniTS.</description>
    </data>
    <data>
        <name>EJournal</name>
        <description>Formato per le riviste elettroniche UniTS.</description>
    </data>
    <data>
        <name>Eut</name>
        <description>Formato per le pubblicazioni EUT.</description>
    </data>
    <data>
        <name>Eutmarc</name>
        <description>Formato per le pubblicazioni EUT.</description>
    </data>
    <data>
        <name>PregressoImages_sutrs</name>
        <description>Formato per l'indice delle schedine pregresso UniTS.</description>
    </data>
</root>
